// <auto-generated />
using System;
using ExternalIntegration.Service.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExternalIntegration.Service.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260801123703_addManifest1_DischargeTerminalCodeNullable")]
    partial class addManifest1_DischargeTerminalCodeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.DischargePermit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CargoOwnerIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerPartyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepPartyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoOwnerRepType")
                        .HasColumnType("int");

                    b.Property<int>("CargoOwnerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StorageAgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StorageAgreementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageAgreementNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageAgreementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Terminal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DischargePermits", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.GoodwayBill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AcceptedWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BlNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlTraceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BulkList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CargoOwnerBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoOwnerCellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CargoOwnerRepBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoOwnerRepCellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoOwnerRepType")
                        .HasColumnType("int");

                    b.Property<int?>("CargoOwnerType")
                        .HasColumnType("int");

                    b.Property<string>("CargoOwnerTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDestinationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityDestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityOriginCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityOriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeNationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsignerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsignerNationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DischargeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DischargeStateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GoodGrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoodHSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GoodNetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoodPackageQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoodPackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodPackageTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GoodPackageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("GoodTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GoodVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDischarge")
                        .HasColumnType("bit");

                    b.Property<int>("InquiryState")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("bit");

                    b.Property<string>("OriginStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RealWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StorageAgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StorageAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageAgreementNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TaskIsRead")
                        .HasColumnType("bit");

                    b.Property<string>("TaskOwnerRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskOwnerRoleNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskRegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskStageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransportationCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportationCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDriverCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDriverPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehiclePlateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VehiclePlateNoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehiclePlateNoSegmentedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WagonTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Workflow")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GoodwayBills", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.IssueRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BulkList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralCargoList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageAgreementNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskRegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Terminal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssueRequests", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEDI")
                        .HasColumnType("bit");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManifestRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Signed")
                        .HasColumnType("bit");

                    b.Property<string>("TerminalCodeDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCodeLoading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voyage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manifests", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.StoreReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BulkList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomsProcedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsProcedureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomsProcedureId")
                        .HasColumnType("int");

                    b.Property<bool?>("DangerousNotNoticed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstDischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralCargoList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodClassificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InquiryLastTryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InquiryState")
                        .HasColumnType("int");

                    b.Property<string>("InquiryStateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIssued")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerCellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OwnerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRepAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OwnerRepBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerRepCellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRepEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRepIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerRepPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerRepPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerRepType")
                        .HasColumnType("int");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity_Reserved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreReceipts", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Terminals", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.Voyage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Etd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsContainerized")
                        .HasColumnType("bit");

                    b.Property<string>("LastPortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextPortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NoticeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoticeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortOfDischargeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortOfLoadingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAgentCompanyIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShippingLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoyageNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Voyages", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Infrastructure.Logging.Entities.PMOLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Logging", "PMOLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
