// <auto-generated />
using System;
using ExternalIntegration.Service.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExternalIntegration.Service.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260505115716_goodwaybill")]
    partial class goodwaybill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.GoodwayBill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AcceptedWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BlNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlTraceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BulkList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CargoOwnerBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoOwnerCellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CargoOwnerRepBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoOwnerRepCellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwnerRepName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoOwnerRepType")
                        .HasColumnType("int");

                    b.Property<int?>("CargoOwnerType")
                        .HasColumnType("int");

                    b.Property<string>("CargoOwnerTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityDestinationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityDestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityOriginCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityOriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeNationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsignerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsignerNationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DischargeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DischargeStateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GoodGrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoodHSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GoodNetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoodPackageQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoodPackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodPackageTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GoodPackageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("GoodTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GoodVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDischarge")
                        .HasColumnType("bit");

                    b.Property<int>("InquiryState")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("bit");

                    b.Property<string>("OriginStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerRep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RealWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StorageAgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StorageAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageAgreementNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TaskIsRead")
                        .HasColumnType("bit");

                    b.Property<string>("TaskOwnerRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskOwnerRoleNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskRegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskStageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransportationCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportationCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDriverCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDriverPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehiclePlateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VehiclePlateNoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehiclePlateNoSegmentedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WagonTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Workflow")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GoodwayBills", (string)null);
                });

            modelBuilder.Entity("ExternalIntegration.Service.Domain.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Terminals", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
