// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDM.Infrastructure.Persistence;

#nullable disable

namespace TDM.Infrastructure.Migrations
{
    [DbContext(typeof(TDMDbContext))]
    [Migration("20260824080400_add-cargotype-to-manifestitem")]
    partial class addcargotypetomanifestitem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TDM.Domain.Entities.ArrivalType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ArrivalTypes", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.CargoType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CargoTypes", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Commodities", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EconomicCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Companies", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContainerTypeAndSizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("ContainerTypeAndSizeId");

                    b.ToTable("Containers", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ContainerTypeAndSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeAndSize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeAndSizeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ContainerTypesAndSizes", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Countries", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Declaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsigneeRepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IpasDeclarationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpasDeclarationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IpasDeclarationReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrafficId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("ConsigneeRepId");

                    b.HasIndex("TrafficId");

                    b.ToTable("Declarations", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeclarationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("DeclarationItemId");

                    b.ToTable("DeclarationContainers", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationContainerGood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeclarationContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("DeclarationContainerId");

                    b.HasIndex("PackageId");

                    b.ToTable("DeclarationContainerGoods", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("CommodityId");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("PackageId");

                    b.ToTable("DeclarationItems", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EnterDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("Gates", "operation");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ETD")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ManifestRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoticeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShipLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VoyageNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Manifests", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContainerId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DangerousCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("IgnitionTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IgnitionTemperatureUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ManifestItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SealNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("ContainerId1");

                    b.HasIndex("ManifestItemId");

                    b.ToTable("ManifestContainers", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestContainerGood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ManifestContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("PackNb")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("ManifestContainerId");

                    b.HasIndex("PackageId");

                    b.ToTable("ManifestContainerGoods", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestGood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ManifestItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("PackNb")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("ManifestItemId");

                    b.HasIndex("PackageId");

                    b.ToTable("ManifestGoods", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consignor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IpasItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManifestItemNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ManifestNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ShipAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShipLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TrafficId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("ManifestId");

                    b.HasIndex("ShipAgentId");

                    b.HasIndex("TrafficId");

                    b.ToTable("ManifestItems", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Packages", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StoreTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreTypeId");

                    b.ToTable("Stores", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DangerousCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IgnitionTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IgnitionTemperatureUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SealNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreReceiptHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("StoreReceiptHeadId");

                    b.ToTable("StoreReceiptContainers", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptContainerGood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DangerousNotNoticed")
                        .HasColumnType("bit");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeavy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNonPalletized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoluminous")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("NoBrandName")
                        .HasColumnType("bit");

                    b.Property<decimal>("PackNB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreReceiptContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("PackageId");

                    b.HasIndex("StoreReceiptContainerId");

                    b.ToTable("StoreReceiptContainerGoods", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptGood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DangerousCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DangerousNotNoticed")
                        .HasColumnType("bit");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IgnitionTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IgnitionTemperatureUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeavy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNonPalletized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoluminous")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("NoBrandName")
                        .HasColumnType("bit");

                    b.Property<decimal>("PackNB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreReceiptHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("PackageId");

                    b.HasIndex("StoreReceiptHeadId");

                    b.ToTable("StoreReceiptGoods", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptHead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArrivalTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsigneeRepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeclarationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FirstDischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPASStoreReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreReceiptStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrafficId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoyageNoticeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalTypeId");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("ConsigneeRepId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("StoreReceiptStateId");

                    b.HasIndex("TrafficId");

                    b.ToTable("StoreReceiptHeads", "doc");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StoreReceiptStates", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StoreTypes", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Terminals", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.TerminalDischarge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CargoTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DangerousCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeclarationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IgnitionTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IgnitionTemperatureUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IpasTerminalDischargeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("IpasTerminalDischargeReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNonPalletized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoluminous")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IssueRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PackNB")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("UnitWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WayBillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WayBillNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("DeclarationItemId");

                    b.HasIndex("StoreId");

                    b.ToTable("TerminalDischarges", "operation");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Traffic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Traffics", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.UserTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserNationalId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("UserTerminals", "basicInfo");
                });

            modelBuilder.Entity("TDM.Domain.Entities.VesselDischarge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DangerousCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("IgnitionTemperature")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("IgnitionTemperatureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("IpasVesselDischargeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("IpasVesselDischargeReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDamaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDangerous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsNonPalletized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVoluminous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ManifestContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManifestItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PackNB")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TerminalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("UnitWeight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("IpasVesselDischargeId")
                        .IsUnique()
                        .HasFilter("[IpasVesselDischargeId] IS NOT NULL");

                    b.HasIndex("ManifestContainerId");

                    b.HasIndex("ManifestItemId");

                    b.HasIndex("StoreId");

                    b.ToTable("VesselDischarges", "operation");
                });

            modelBuilder.Entity("TDM.Domain.Entities.WeightBridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TareWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("WeightBridges", "operation");
                });

            modelBuilder.Entity("TDM.Domain.Entities.City", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Container", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Container", null)
                        .WithMany("ContainerDeclarations")
                        .HasForeignKey("ContainerId");

                    b.HasOne("TDM.Domain.Entities.ContainerTypeAndSize", "ContainerTypeAndSize")
                        .WithMany("Containers")
                        .HasForeignKey("ContainerTypeAndSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContainerTypeAndSize");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Declaration", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Company", "Consignee")
                        .WithMany("ConsigneeDeclarations")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Company", "ConsigneeRep")
                        .WithMany("ConsigneeRepDeclarations")
                        .HasForeignKey("ConsigneeRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Traffic", "Traffic")
                        .WithMany("TrafficDeclarations")
                        .HasForeignKey("TrafficId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeRep");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationContainer", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.DeclarationItem", "DeclarationItem")
                        .WithMany("DeclarationContainers")
                        .HasForeignKey("DeclarationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("DeclarationItem");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationContainerGood", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Commodity", "Commodity")
                        .WithMany("CommodityDeclarationContainerGoods")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.DeclarationContainer", "DeclarationContainer")
                        .WithMany("DeclarationContainerGoods")
                        .HasForeignKey("DeclarationContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Package", "Package")
                        .WithMany("PackageDeclarationContainerGoods")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("DeclarationContainer");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationItem", b =>
                {
                    b.HasOne("TDM.Domain.Entities.CargoType", "CargoType")
                        .WithMany("CargoTypeDeclarationItems")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Commodity", "Commodity")
                        .WithMany("CommodityDeclarationItems")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Declaration", "Declaration")
                        .WithMany("DeclarationItems")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Package", "Package")
                        .WithMany("PackageDeclarationItems")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Commodity");

                    b.Navigation("Declaration");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Gate", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Declaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestContainer", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Container", null)
                        .WithMany("ContainerManifests")
                        .HasForeignKey("ContainerId1");

                    b.HasOne("TDM.Domain.Entities.ManifestItem", "ManifestItem")
                        .WithMany("ManifestContainers")
                        .HasForeignKey("ManifestItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("ManifestItem");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestContainerGood", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Commodity", "Commodity")
                        .WithMany("CommodityManifestContainerGoods")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.ManifestContainer", "ManifestContainer")
                        .WithMany("ManifestContainerGoods")
                        .HasForeignKey("ManifestContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Package", "Package")
                        .WithMany("PackageManifestContainerGoods")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("ManifestContainer");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestGood", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Commodity", "Commodity")
                        .WithMany("CommodityManifestGoods")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.ManifestItem", "ManifestItem")
                        .WithMany("ManifestGoods")
                        .HasForeignKey("ManifestItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Package", "Package")
                        .WithMany("PackageManifestGoods")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("ManifestItem");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestItem", b =>
                {
                    b.HasOne("TDM.Domain.Entities.CargoType", "CargoType")
                        .WithMany("CargoTypeManifestItems")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Company", "Consignee")
                        .WithMany("ConsigneeManifestItems")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Manifest", "Manifest")
                        .WithMany("ManifestItems")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Company", "ShipAgent")
                        .WithMany("ShipAgentManifestItems")
                        .HasForeignKey("ShipAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Traffic", "Traffic")
                        .WithMany("TrafficManifestItems")
                        .HasForeignKey("TrafficId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Consignee");

                    b.Navigation("Manifest");

                    b.Navigation("ShipAgent");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Store", b =>
                {
                    b.HasOne("TDM.Domain.Entities.StoreType", "StoreType")
                        .WithMany("Stores")
                        .HasForeignKey("StoreTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StoreType");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptContainer", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Container", "Container")
                        .WithMany("ContainerStoreReceipts")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.StoreReceiptHead", "StoreReceiptHead")
                        .WithMany("StoreReceiptContainers")
                        .HasForeignKey("StoreReceiptHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("StoreReceiptHead");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptContainerGood", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Commodity", "Commodity")
                        .WithMany("CommodityStoreReceiptContainerGoods")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Package", "Package")
                        .WithMany("PackageStoreReceiptContainerGoods")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.StoreReceiptContainer", "StoreReceiptContainer")
                        .WithMany("StoreReceiptContainerGoods")
                        .HasForeignKey("StoreReceiptContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Package");

                    b.Navigation("StoreReceiptContainer");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptGood", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Commodity", "Commodity")
                        .WithMany("CommodityStoreReceiptGoods")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Package", "Package")
                        .WithMany("PackageStoreReceiptGoods")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.StoreReceiptHead", "StoreReceiptHead")
                        .WithMany("StoreReceiptGoods")
                        .HasForeignKey("StoreReceiptHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Package");

                    b.Navigation("StoreReceiptHead");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptHead", b =>
                {
                    b.HasOne("TDM.Domain.Entities.ArrivalType", "ArrivalType")
                        .WithMany("ArrivalTypeStoreReceiptHeads")
                        .HasForeignKey("ArrivalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.CargoType", "CargoType")
                        .WithMany("CargoTypeStoreReceiptHeads")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Company", "Consignee")
                        .WithMany("ConsigneeStoreReceiptHeads")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Company", "ConsigneeRep")
                        .WithMany("ConsigneeRepStoreReceiptHeads")
                        .HasForeignKey("ConsigneeRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Company", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Declaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId");

                    b.HasOne("TDM.Domain.Entities.StoreReceiptState", "StoreReceiptState")
                        .WithMany("StoreReceiptStateStoreReceiptHeads")
                        .HasForeignKey("StoreReceiptStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Traffic", "Traffic")
                        .WithMany("TrafficStoreReceiptHeads")
                        .HasForeignKey("TrafficId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalType");

                    b.Navigation("CargoType");

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeRep");

                    b.Navigation("Creator");

                    b.Navigation("Declaration");

                    b.Navigation("StoreReceiptState");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("TDM.Domain.Entities.TerminalDischarge", b =>
                {
                    b.HasOne("TDM.Domain.Entities.CargoType", null)
                        .WithMany("CargoTypeTerminalDischarges")
                        .HasForeignKey("CargoTypeId");

                    b.HasOne("TDM.Domain.Entities.DeclarationItem", "DeclarationItem")
                        .WithMany("TerminalDischarges")
                        .HasForeignKey("DeclarationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Store", "Store")
                        .WithMany("StoreTerminalDischarges")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeclarationItem");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("TDM.Domain.Entities.UserTerminal", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Terminal", "Terminal")
                        .WithMany("UserTerminals")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("TDM.Domain.Entities.VesselDischarge", b =>
                {
                    b.HasOne("TDM.Domain.Entities.ManifestContainer", "ManifestContainer")
                        .WithMany("ManifestContainerVesselDischarges")
                        .HasForeignKey("ManifestContainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TDM.Domain.Entities.ManifestItem", "ManifestItem")
                        .WithMany("ManifestItemVesselDischarges")
                        .HasForeignKey("ManifestItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDM.Domain.Entities.Store", "Store")
                        .WithMany("StoreVesselDischarges")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManifestContainer");

                    b.Navigation("ManifestItem");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("TDM.Domain.Entities.WeightBridge", b =>
                {
                    b.HasOne("TDM.Domain.Entities.Declaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ArrivalType", b =>
                {
                    b.Navigation("ArrivalTypeStoreReceiptHeads");
                });

            modelBuilder.Entity("TDM.Domain.Entities.CargoType", b =>
                {
                    b.Navigation("CargoTypeDeclarationItems");

                    b.Navigation("CargoTypeManifestItems");

                    b.Navigation("CargoTypeStoreReceiptHeads");

                    b.Navigation("CargoTypeTerminalDischarges");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Commodity", b =>
                {
                    b.Navigation("CommodityDeclarationContainerGoods");

                    b.Navigation("CommodityDeclarationItems");

                    b.Navigation("CommodityManifestContainerGoods");

                    b.Navigation("CommodityManifestGoods");

                    b.Navigation("CommodityStoreReceiptContainerGoods");

                    b.Navigation("CommodityStoreReceiptGoods");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Company", b =>
                {
                    b.Navigation("ConsigneeDeclarations");

                    b.Navigation("ConsigneeManifestItems");

                    b.Navigation("ConsigneeRepDeclarations");

                    b.Navigation("ConsigneeRepStoreReceiptHeads");

                    b.Navigation("ConsigneeStoreReceiptHeads");

                    b.Navigation("ShipAgentManifestItems");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Container", b =>
                {
                    b.Navigation("ContainerDeclarations");

                    b.Navigation("ContainerManifests");

                    b.Navigation("ContainerStoreReceipts");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ContainerTypeAndSize", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Declaration", b =>
                {
                    b.Navigation("DeclarationItems");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationContainer", b =>
                {
                    b.Navigation("DeclarationContainerGoods");
                });

            modelBuilder.Entity("TDM.Domain.Entities.DeclarationItem", b =>
                {
                    b.Navigation("DeclarationContainers");

                    b.Navigation("TerminalDischarges");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Manifest", b =>
                {
                    b.Navigation("ManifestItems");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestContainer", b =>
                {
                    b.Navigation("ManifestContainerGoods");

                    b.Navigation("ManifestContainerVesselDischarges");
                });

            modelBuilder.Entity("TDM.Domain.Entities.ManifestItem", b =>
                {
                    b.Navigation("ManifestContainers");

                    b.Navigation("ManifestGoods");

                    b.Navigation("ManifestItemVesselDischarges");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Package", b =>
                {
                    b.Navigation("PackageDeclarationContainerGoods");

                    b.Navigation("PackageDeclarationItems");

                    b.Navigation("PackageManifestContainerGoods");

                    b.Navigation("PackageManifestGoods");

                    b.Navigation("PackageStoreReceiptContainerGoods");

                    b.Navigation("PackageStoreReceiptGoods");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Store", b =>
                {
                    b.Navigation("StoreTerminalDischarges");

                    b.Navigation("StoreVesselDischarges");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptContainer", b =>
                {
                    b.Navigation("StoreReceiptContainerGoods");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptHead", b =>
                {
                    b.Navigation("StoreReceiptContainers");

                    b.Navigation("StoreReceiptGoods");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreReceiptState", b =>
                {
                    b.Navigation("StoreReceiptStateStoreReceiptHeads");
                });

            modelBuilder.Entity("TDM.Domain.Entities.StoreType", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Terminal", b =>
                {
                    b.Navigation("UserTerminals");
                });

            modelBuilder.Entity("TDM.Domain.Entities.Traffic", b =>
                {
                    b.Navigation("TrafficDeclarations");

                    b.Navigation("TrafficManifestItems");

                    b.Navigation("TrafficStoreReceiptHeads");
                });
#pragma warning restore 612, 618
        }
    }
}
