<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BasicInformation\Cities\Commands\UpdateCity - Copy\**" />
    <EmbeddedResource Remove="BasicInformation\Cities\Commands\UpdateCity - Copy\**" />
    <None Remove="BasicInformation\Cities\Commands\UpdateCity - Copy\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TDM.Domain\TDM.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Doc\IssueRequestStoreReceipts\Commands\DTOs\" />
  </ItemGroup>

</Project>
