namespace ExternalIntegration.Service.Infrastructure.Integrations.PMO.Responses
{
    public class GoodwayBillResultDto
    {
        public string? Id { get; set; }
        public int SerialNo { get; set; }
        public Guid? StorageAgreementId { get; set; }
        public string? StorageAgreementNo { get; set; }
        public DateTime? StorageAgreementDate { get; set; }
        public Guid TerminalId { get; set; }
        public string? TerminalCode { get; set; }
        public string? Terminal { get; set; }
        public Guid PortId { get; set; }
        public string? Port { get; set; }
        public string? BlNo { get; set; }
        public DateTime Date { get; set; }
        public string? TransportationCompany { get; set; }
        public string? TransportationCompanyCode { get; set; }
        public string? ConsignerName { get; set; }
        public string? ConsignerNationalCode { get; set; }
        public string? ConsigneeName { get; set; }
        public string? ConsigneeNationalCode { get; set; }
        public string? CityOrigin { get; set; }
        public Guid? CityOriginId { get; set; }
        public string? CityDestination { get; set; }
        public Guid? CityDestinationId { get; set; }
        public string? VehiclePlateNo { get; set; }
        public string? VehicleDriverName { get; set; }
        public string? VehicleDriverCardNo { get; set; }
        public string? VehicleDriverPhone { get; set; }
        public string? GoodTitle { get; set; }
        public string? GoodType { get; set; }
        public string? GoodPackageType { get; set; }
        public int? GoodPackageTypeId { get; set; }
        public decimal GoodPackageQuantity { get; set; }
        public string? GoodHSCode { get; set; }
        public decimal? GoodGrossWeight { get; set; }
        public decimal? GoodNetWeight { get; set; }
        public decimal? GoodVolume { get; set; }
        public int StateId { get; set; }
        public string? State { get; set; }
        public DateTime? EstimatedArrivalDate { get; set; }
        public string? TaskId { get; set; }
        public string? TaskOwnerRoleName { get; set; }
        public string? TaskStage { get; set; }
        public string? TaskStageName { get; set; }
        public string? TaskOwnerRoleNames { get; set; }
        public bool? TaskIsRead { get; set; }
        public DateTime? TaskRegisterDate { get; set; }
        public string? TaskRemark { get; set; }
        public string? Workflow { get; set; }
        public string? CargoOwnerName { get; set; }
        public string? CargoOwnerIdNumber { get; set; }
        public int? CargoOwnerType { get; set; }
        public string? CargoOwnerRepName { get; set; }
        public string? CargoOwnerRepIdNumber { get; set; }
        public int CargoOwnerRepType { get; set; }
        public int InquiryState { get; set; }
        public string? PortCode { get; set; }
        public string? BlTraceCode { get; set; }
        public int Type { get; set; }
        public string? TypeName { get; set; }
        public string? CityOriginCode { get; set; }
        public string? CityDestinationCode { get; set; }
        public Guid? VehiclePlateNoModelId { get; set; }
        public string? VehiclePlateNoSegmentedValue { get; set; }
        public string? GoodPackageTypeCode { get; set; }
        public string? OriginStation { get; set; }
        public string? DestinationStation { get; set; }
        public string? WagonNo { get; set; }
        public string? WagonOwner { get; set; }
        public decimal? RealWeight { get; set; }
        public decimal? AcceptedWeight { get; set; }
        public string? Owner { get; set; }
        public string? OwnerRep { get; set; }
        public int? WagonTypeId { get; set; }
        public string? WagonType { get; set; }
        public string? CargoOwnerCellPhone { get; set; }
        public DateTime? CargoOwnerBirthDate { get; set; }
        public string? CargoOwnerTypeName { get; set; }
        public string? CargoOwnerRepCellPhone { get; set; }
        public DateTime? CargoOwnerRepBirthDate { get; set; }
        public bool IsReturn { get; set; }
        public bool HasDischarge { get; set; }
        public Guid? DischargeId { get; set; }
        public int? DischargeStateId { get; set; }
        public DateTime CreationDate { get; set; }
        public List<BulkResultDto>? BulkList { get; set; }
        public List<GeneralCargoResultDto>? CargoList { get; set; }
        public List<ContainerResultDto>? ContainerList { get; set; }
    }
}
